# Generated by Django 6.0.5 on 2026-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='recovery_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_solutions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
