# Generated by Django 6.0.5 on 2026-05-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
