# Generated by Django 6.0.5 on 2026-05-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('batuk_kering', models.IntegerField(default=0)),
                ('batuk_berdahak', models.IntegerField(default=0)),
                ('demam', models.IntegerField(default=0)),
                ('pilek', models.IntegerField(default=0)),
                ('hidung_tersumbat', models.IntegerField(default=0)),
                ('sesak_napas', models.IntegerField(default=0)),
                ('nyeri_tenggorokan', models.IntegerField(default=0)),
                ('sakit_kepala', models.IntegerField(default=0)),
                ('mual_muntah', models.IntegerField(default=0)),
                ('nyeri_dada', models.IntegerField(default=0)),
                ('suara_serak', models.IntegerField(default=0)),
                ('kelelahan', models.IntegerField(default=0)),
                ('berkeringat_malam', models.IntegerField(default=0)),
                ('nafsu_makan_turun', models.IntegerField(default=0)),
                ('hilang_penciuman', models.IntegerField(default=0)),
                ('nyeri_saat_menelan', models.IntegerField(default=0)),
                ('diagnosis', models.CharField(max_length=100)),
            ],
        ),
    ]
